export const wishes = {
  1: "May your days be as authentic and beautiful as your soul",
  2: "Sending you the magic of frosty mornings and starry nights",
  3: "May your journey be as vibrant and unique as you are",
  4: "Sending a gentle reminder that you are loved and valued",
  5: "May your holiday be as magical and unique as a snowflake",
  6: "In case nobody told you today, you’re amazing",
  7: "May your day be filled with love, laughter, and heartfelt connections",
  8: "Sending you warmth and positivity to brighten your day",
  9: "Wishing you the joy of giving and the comfort of receiving",
  10: "Sending you the joy of connection and the warmth of togetherness",
  11: "Wishing you strength and serenity in all that you do",
  12: "May your holiday card carry the magic of the season to your loved ones",
  13: "Hope you feel steadier, stronger and better each day",
  14: "Please take care of yourself today",
  15: "Be kinder to yourself",
  16: "Hope life’s been kind to you",
  17: "Sending a little sunshine your way",
  18: "Hoping the best of luck always finds its way to you",
  19: "May happiness, love, and success follow you wherever you go",
  20: "Wishing you joy and endless smiles today",
  21: "Relax and unwind. You deserve it!",
  22: "Nobody is perfect, but you're so close",
  23: "Laugh more and stress less this time",
  24: "May all your dreams come true!", 
};